services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  bit_score:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8182:8182"
